### ISSUE TITLE
ExGherkin

### ISSUE THREAD

**Issue by Ajwah** [WannesFransen1994/ex_gherkin#1]
Hi there!
It is lovely to meet others who love Cucumber!

I just stumbled on [an issue you posted](https://github.com/cucumber/cucumber/issues/1046) making me realize that you are also implementing a Gherkin parser. It may be beneficial for you to know that I have [implemented one](https://github.com/Ajwah/ex-gherkin) about half a year ago and that I just finished with [ex_cucumber](https://github.com/Ajwah/ex_cucumber). 

I certainly encourage you to continue your work and if your implementation ends up being better than my one, then I will use it for `ex_cucumber` instead :). In the meanwhile, it would perhaps be nice to connect with one and another.

**Comment by WannesFransen1994** [comment]
Hello,

Thank you for your message! Wow if I'd only known... I completely agree, if you're on slack, feel free to DM me (WFrans) or on elixirforum as WFransen. Just a matter that we don't hold a huge conversation over GitHub issues ;)

Personally my goal is to get into the cucumber monorepo. Hence also the use of the .razor.exs file. The code should be able to be maintained by non-elixir users, hence the similarity with the Java code in its monorepo. I'm not sure about the reporter implementations in other languages etc, but if I'm correct they also use messages to facilitate communication. Maybe, and I'm really hopeful here, there could be some possibilities to let your ex_cucumber and this ex_gherkin work together.

Anyway, let us discuss this further on another channel? Hoping to finish this project this / next week, and the week after that to see what's necessary to get into the monorepo. Looking forward to your message!

**Comment by WannesFransen1994** [comment]
After long and meaningful discussions, we've decided that this ex_gherkin implementation is not directly compatible with the requirements for the ex_cucumber library. 

Hence we'll aim for this to be integrated in the monorepo, after which the following steps will be taken (with no guarantees when this will be delivered):

1. Integrate into the cucumber mono repo (cucumber messages & gherkin parser)
2. Look at other language implementations for the cucumber implementations (& consult with the cucumber open source team)
3. identify key parts / make a rough design of the ex_cucumber implementation, what parts will need to be a standalone library, which aren't, and so on.
4. start coding in a structural manner which is clear for the community so that contributions can be made at any point in time.

While this is an issue here, it's actually the plan for a next library. Hence that we are closing this!
